apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 921224219116.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 921224219116.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 435e0e24
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
